import { Document, DocStatus, DocKind } from '../../schema';

export class DocStore {
  private docs = new Map<string, Document>();
  private counter = 0;

  private makeId(): string {
    return `doc-${++this.counter}`;
  }

  private now(): string {
    return new Date().toISOString();
  }

  create(partial: Omit<Document, 'id' | 'createdAt' | 'updatedAt'>): Document {
    const id = this.makeId();
    const doc: Document = {
      ...partial,
      id,
      createdAt: this.now(),
      updatedAt: this.now(),
    };
    this.docs.set(id, doc);
    return doc;
  }

  get(id: string): Document | undefined {
    return this.docs.get(id);
  }

  list(filter?: { status?: DocStatus; kind?: DocKind; tags?: string[]; autoGenerated?: boolean }): Document[] {
    let results = Array.from(this.docs.values());
    if (filter?.status) results = results.filter(d => d.status === filter.status);
    if (filter?.kind) results = results.filter(d => d.kind === filter.kind);
    if (filter?.tags) results = results.filter(d => filter.tags!.some(t => d.tags.includes(t)));
    if (filter?.autoGenerated !== undefined) results = results.filter(d => d.autoGenerated === filter.autoGenerated);
    return results.sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime());
  }

  update(id: string, changes: Partial<Omit<Document, 'id' | 'createdAt'>>): Document | undefined {
    const existing = this.docs.get(id);
    if (!existing) return undefined;
    const updated: Document = { ...existing, ...changes, updatedAt: this.now() };
    this.docs.set(id, updated);
    return updated;
  }

  delete(id: string): boolean {
    return this.docs.delete(id);
  }
}
