/**
 * Core schema types for the AI-Native Notion Operating System
 */

// ─── Common ───

export type Status = 'backlog' | 'todo' | 'in_progress' | 'review' | 'done' | 'cancelled';
export type Priority = 'low' | 'medium' | 'high' | 'critical';

export interface Timestamped {
  createdAt: string;   // ISO 8601
  updatedAt: string;
}

export interface Assignable {
  assigneeId?: string;     // agent or user ID
  assigneeName?: string;
}

// ─── Task Tracking ───

export interface Task extends Timestamped, Assignable {
  id: string;
  identifier: string;       // e.g. "TEC-42"
  title: string;
  description: string;
  status: Status;
  priority: Priority;
  tags: string[];
  parentId?: string;        // for subtasks
  estimatedHours?: number;
  actualHours?: number;
  sprintId?: string;
  roadmapItemId?: string;
  notionPageId?: string;
}

// ─── Roadmap ───

export type RoadmapTimeframe = 'quarter' | 'half' | 'year';

export interface RoadmapItem extends Timestamped, Assignable {
  id: string;
  title: string;
  description: string;
  status: Status;
  priority: Priority;
  timeframe: RoadmapTimeframe;
  targetDate: string;       // ISO 8601
  dependencies: string[];   // IDs of blocking items
  progressPercent: number;
  notionPageId?: string;
}

// ─── Bug Tracking ───

export type BugSeverity = 'trivial' | 'minor' | 'major' | 'critical' | 'blocker';
export type BugEnvironment = 'local' | 'staging' | 'production' | 'ci';

export interface Bug extends Timestamped, Assignable {
  id: string;
  identifier: string;
  title: string;
  description: string;
  reproductionSteps: string[];
  expectedBehavior: string;
  actualBehavior: string;
  severity: BugSeverity;
  environment: BugEnvironment;
  status: Status;
  relatedTaskId?: string;
  regressionFrom?: string;  // commit or release
  notionPageId?: string;
}

// ─── Engineering Memory ───

export type MemoryKind = 'decision' | 'lesson' | 'architecture' | 'process' | 'incident';

export interface EngineeringMemory extends Timestamped {
  id: string;
  kind: MemoryKind;
  title: string;
  context: string;
  decision: string;
  consequences: string[];
  alternativesConsidered: string[];
  participants: string[];
  tags: string[];
  relatedTaskIds: string[];
  notionPageId?: string;
}

// ─── Documentation ───

export type DocStatus = 'draft' | 'review' | 'published' | 'archived';
export type DocKind = 'api' | 'runbook' | 'adr' | 'guide' | 'reference';

export interface Document extends Timestamped, Assignable {
  id: string;
  title: string;
  kind: DocKind;
  status: DocStatus;
  content: string;          // markdown
  tags: string[];
  autoGenerated: boolean;
  sourceRef?: string;       // e.g. git commit or file path
  notionPageId?: string;
}

// ─── Sprint ───

export interface Sprint extends Timestamped {
  id: string;
  name: string;
  goal: string;
  startDate: string;
  endDate: string;
  status: 'planning' | 'active' | 'closed';
  taskIds: string[];
  velocity?: number;        // story points or hours completed
  notionPageId?: string;
}

// ─── AI Summary ───

export interface AISummary extends Timestamped {
  id: string;
  scope: 'task' | 'sprint' | 'roadmap' | 'project';
  scopeId: string;
  summaryText: string;
  keyInsights: string[];
  risks: string[];
  recommendations: string[];
  generatedBy: string;      // model identifier
}

// ─── Notion Sync ───

export interface NotionSyncState extends Timestamped {
  id: string;
  entityType: 'task' | 'roadmap' | 'bug' | 'memory' | 'doc' | 'sprint';
  entityId: string;
  notionPageId: string;
  lastSyncedAt: string;
  syncVersion: number;
  checksum: string;
}
