import { describe, it, expect, beforeEach } from 'vitest';
import { TaskStore } from '../src/modules/tasks';
import { SprintStore } from '../src/modules/sprints';
import { RoadmapStore } from '../src/modules/roadmap';
import { BugStore } from '../src/modules/bugs';
import { MemoryStore } from '../src/modules/memory';
import { DocStore } from '../src/modules/docs';
import { AISummarizer } from '../src/ai';
import { startSprintWorkflow, completeTaskWorkflow, dailyStandupWorkflow, closeSprintWorkflow } from '../src/workflows';

describe('TaskStore', () => {
  let store: TaskStore;
  beforeEach(() => { store = new TaskStore(); });

  it('creates and retrieves a task', () => {
    const t = store.create({ title: 'Test', description: 'Desc', status: 'todo', priority: 'high', tags: [] });
    expect(t.identifier).toMatch(/^TEC-\d+$/);
    expect(store.get(t.id)?.title).toBe('Test');
  });

  it('filters by status', () => {
    store.create({ title: 'A', description: '', status: 'todo', priority: 'low', tags: [] });
    store.create({ title: 'B', description: '', status: 'done', priority: 'low', tags: [] });
    expect(store.list({ status: 'todo' }).length).toBe(1);
  });
});

describe('SprintStore', () => {
  let store: SprintStore;
  beforeEach(() => { store = new SprintStore(); });

  it('tracks active sprint', () => {
    const s = store.create({ name: 'S1', goal: 'G', startDate: '2026-01-01', endDate: '2026-01-14', status: 'active', taskIds: [] });
    expect(store.active()?.id).toBe(s.id);
  });
});

describe('RoadmapStore', () => {
  let store: RoadmapStore;
  beforeEach(() => { store = new RoadmapStore(); });

  it('detects blocked items', () => {
    const a = store.create({ title: 'A', description: '', status: 'todo', priority: 'high', timeframe: 'quarter', targetDate: '2026-06-01', dependencies: [], progressPercent: 0 });
    const b = store.create({ title: 'B', description: '', status: 'todo', priority: 'high', timeframe: 'quarter', targetDate: '2026-06-01', dependencies: [a.id], progressPercent: 0 });
    expect(store.blockedItems().map(x => x.id)).toContain(b.id);
  });
});

describe('BugStore', () => {
  let store: BugStore;
  beforeEach(() => { store = new BugStore(); });

  it('finds critical open bugs', () => {
    store.create({ title: 'Crash', description: '', reproductionSteps: [], expectedBehavior: '', actualBehavior: '', severity: 'critical', environment: 'production', status: 'todo' });
    store.create({ title: 'Typo', description: '', reproductionSteps: [], expectedBehavior: '', actualBehavior: '', severity: 'minor', environment: 'production', status: 'todo' });
    expect(store.criticalOpen().length).toBe(1);
  });
});

describe('MemoryStore', () => {
  let store: MemoryStore;
  beforeEach(() => { store = new MemoryStore(); });

  it('searches by keyword', () => {
    store.create({ kind: 'decision', title: 'Use Postgres', context: 'DB choice', decision: 'Postgres', consequences: [], alternativesConsidered: [], participants: [], tags: [], relatedTaskIds: [] });
    store.create({ kind: 'lesson', title: 'Cache Redis', context: 'Perf', decision: 'Redis', consequences: [], alternativesConsidered: [], participants: [], tags: [], relatedTaskIds: [] });
    expect(store.search('Postgres').length).toBe(1);
  });
});

describe('DocStore', () => {
  let store: DocStore;
  beforeEach(() => { store = new DocStore(); });

  it('filters auto-generated docs', () => {
    store.create({ title: 'API', kind: 'api', status: 'published', content: '# API', tags: [], autoGenerated: true });
    store.create({ title: 'Guide', kind: 'guide', status: 'published', content: '# Guide', tags: [], autoGenerated: false });
    expect(store.list({ autoGenerated: true }).length).toBe(1);
  });
});

describe('Workflows', () => {
  const makeCtx = () => ({
    tasks: new TaskStore(),
    sprints: new SprintStore(),
    roadmap: new RoadmapStore(),
    bugs: new BugStore(),
    memory: new MemoryStore(),
    docs: new DocStore(),
    ai: new AISummarizer({ apiKey: 'test' }),
  });

  it('startSprintWorkflow moves todos to in_progress', () => {
    const ctx = makeCtx();
    const t = ctx.tasks.create({ title: 'T', description: '', status: 'todo', priority: 'medium', tags: [] });
    const s = ctx.sprints.create({ name: 'S', goal: 'G', startDate: '2026-01-01', endDate: '2026-01-14', status: 'planning', taskIds: [t.id] });
    const moved = startSprintWorkflow(ctx, s.id);
    expect(moved).toBe(1);
    expect(ctx.tasks.get(t.id)?.status).toBe('in_progress');
  });

  it('completeTaskWorkflow updates roadmap progress', async () => {
    const ctx = makeCtx();
    const r = ctx.roadmap.create({ title: 'R', description: '', status: 'in_progress', priority: 'high', timeframe: 'quarter', targetDate: '2026-06-01', dependencies: [], progressPercent: 0 });
    const t = ctx.tasks.create({ title: 'T', description: '', status: 'in_progress', priority: 'high', tags: [], roadmapItemId: r.id });
    const result = await completeTaskWorkflow(ctx, t.id);
    expect(result.roadmapUpdated).toBe(true);
    expect(ctx.roadmap.get(r.id)?.progressPercent).toBe(100);
  });

  it('closeSprintWorkflow moves unfinished to backlog', () => {
    const ctx = makeCtx();
    const t = ctx.tasks.create({ title: 'T', description: '', status: 'in_progress', priority: 'medium', tags: [] });
    const s = ctx.sprints.create({ name: 'S', goal: 'G', startDate: '2026-01-01', endDate: '2026-01-14', status: 'active', taskIds: [t.id] });
    const moved = closeSprintWorkflow(ctx, s.id);
    expect(moved).toBe(1);
    expect(ctx.tasks.get(t.id)?.status).toBe('backlog');
    expect(ctx.tasks.get(t.id)?.sprintId).toBeUndefined();
  });
});
